### ISSUE TITLE
Sprite Multiplexor - Z ordering

### ISSUE THREAD

**Issue by robin-raymond** [martinpiper/C64Public#10]
Does the sprite multiplexor handle Z ordering so the sprites can be layered?

**Comment by martinpiper** [comment]
The sort used in the multiplexor is stable, meaning it will maintain the ordering of elements if they have the same Y position.
If that is combined with Multiplex_MaintainPriority=1 then the multiplexor will try its hardest to maintain sprite ordering so they can be layered. The attached example shows the effect. Each moving blob uses two sprites to show their relative sprite priority is maintained. However, if the sprite formation gets very busy, then the sprite ordering is not maintained.
[TestMultiplexor.zip](https://github.com/user-attachments/files/17690137/TestMultiplexor.zip)
