### ISSUE TITLE
Music Studio and export using hex address

### ISSUE THREAD

**Issue by robin-raymond** [martinpiper/C64Public#4]
For Music Studio, you have an example:

````
*=$c000
	; Turn off IRQs and initialise music track 0
	sei
	lda #$00
	jsr $1000
	; Now wait for the raster at $80
.loop
	lda #$80
.wait
	cmp $d012
	bne .wait
	; Play one frame of music and then loop around again
	jsr $1003
	jmp .loop
````

I need to be able to export and load/run the output $E400. That means I have to export using "Output just the player and data" since that's the only option that allows specifying a specific run hex address. What I'm unclear about is what is the offset for the entry points since I assume there's some kind of header to the output file? I'm assuming the output is a pure .bin file ready to run? If it's not, what is it? When I export to $E400 the first byte in the .bin is $00 (BRK) so that can't be right. If I export to $E400 and load at $E400, what value $E400 + N  and $E400 + N + 3 is correct for the two entry points? Or do I need to strip some prefix headers? Or export to some other value as $E400 + M, but then load to $E400 but jump to $E400 + M? Any help would be appreciated.

**Comment by robin-raymond** [comment]
````
00 E4 4C 05 E6 4C 78 E6 4C AC EA 4D 53 32 32 00
...
````
I should have just looked closer at the binary, as it's become obvious! I realize the output is actually a .prg (althourgh the app doesn't use the PRG extension during the input as a default). `00 E4` is the .prg location, and the `$4C` is the `JMP` instruction, followed by the memory location, followed by two other `JMP` instructions making up the full jump table.

**Comment by martinpiper** [comment]
Yes, the file is a prg, it has the lo/hi bytes at the start :)
This "how to play from BASIC" video talks about the music prg file start address: https://youtu.be/s9IgipH5vXw?t=77
And this loads the same prg into memory and playing it from machine code by writing the code in the Vice emulator monitor: https://youtu.be/NRzS6oS9JLo?t=29
